source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'BaseProj' do
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Mantle', 		'~> 2.1.0'
	pod 'Aspects', 		'~> 1.4.1'
	pod 'SDWebImage', 	'~> 4.0.0'
	pod 'Masonry', 		'~> 1.0.2'
	pod 'CocoaLumberjack', '~> 3.2.0'
    pod 'SDVersion', '~> 4.0.2'
    pod 'MLTransition', '~> 2.1.2'
end
